name: shell commands
on:
  push:
  pull_request:
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: echo string
      run: echo "Hello"
    - name: Multi line string 
      run: |
        pwd 
        node -v
        ls -a


